module.exports = {

    //  1.x.x INFORMATIONAL HTTP Response Codes
    CONTINUE: {status_code: 100, error: ``},
    SWITCHING_PROTOCOLS: {status_code: 101, error: ``},
    PROCESSING: {status_code: 102, error: ``},
    EARLY_HINTS: {status_code: 103, error: ``},

    //  2.x.x SUCCESS HTTP Response Codes
    OK: {status_code: 200, error: ``},
    CREATED: {status_code: 201, error: ``},
    ACCEPTED: {status_code: 202, error: ``},
    NON_AUTHORITATIVE_INFO: {status_code: 203, error: ``},
    NO_CONTENT: {status_code: 204, error: ``},
    RESET_CONTENT: {status_code: 205, error: ``},
    PARTIAL_CONTENT: {status_code: 206, error: ``},
    MULTI_STATUS: {status_code: 207, error: ``},
    ALREADY_REPORTED: {status_code: 208, error: ``},
    IM_USED: {status_code: 226, error: ``},

    //  3.x.x REDIRECTION HTTP Response Codes
    MULTIPLE_CHOICES: {status_code: 300, error: ``},
    MOVED_PERMANENTLY: {status_code: 301, error: ``},
    FOUND: {status_code: 302, error: ``},
    SEE_OTHER: {status_code: 303, error: ``},
    NOT_MODIFIED: {status_code: 304, error: ``},
    USE_PROXY: {status_code: 305, error: ``},
    TEMPORARY_REDIRET: {status_code: 307, error: ``},
    PERMANENT_REDIRECT: {status_code: 308, error: ``},

    //  4.x.x CLIENT ERRORS HTTP Response Codes
    BAD_REQUEST: {status_code: 400, error: ``},
    UNAUTHORIZATED: {status_code: 401, error: ``},
    PAYMENT_REQUIRED: {status_code: 402, error: ``},
    FORBIDDEN: {status_code: 403, error: ``},
    NOT_FOUND: {status_code: 404, error: ``},
    METHOD_NOT_ALLOWED: {status_code: 405, error: ``},
    NOT_ACCEPTABLE: {status_code: 406, error: ``},
    PROXY_AUTH_REQUIRED: {status_code: 407, error: ``},
    REQUEST_TIMEOUT: {status_code: 408, error: ``},
    CONFLICT: {status_code: 409, error: ``},
    GONE: {status_code: 410, error: ``},
    LENGTH_REQUIRED: {status_code: 411, error: ``},
    PRECONDITION_FAILED: {status_code: 412, error: ``},
    PAYLOAD_TOO_LARGE: {status_code: 413, error: ``},
    URI_TOO_LONG: {status_code: 414, error: ``},
    UNSUPPORTED_MEDIA_TYPE: {status_code: 415, error: ``},
    RANGE_NOT_SATSIABLE: {status_code: 416, error: ``},
    EXPECTATUIB_FAILED: {status_code: 417, error: ``},
    MISDIRECTED_REQUEST: {status_code: 421, error: ``},
    UNPROCESSABLE_ENTITY: {status_code: 422, error: ``},
    LOCKED: {status_code: 423, error: ``},
    FAILED_DEPENDENCY: {status_code: 424, error: ``},
    UPGRADE_REQUIRED: {status_code: 426, error: ``},
    PRECONDITION_REQUIRED: {status_code: 428, error: ``},
    TOO_MANY_REQUESTS: {status_code: 429, error: ``},
    REQUEST_HEADER_FIELDS_TOO_LARGE: {status_code: 431, error: ``},
    UNAVAILABLE_FOR_LEGAL_REASONS: {status_code: 451, error: ``},

    //  5.x.x SERVER ERRORS HTTP Response Codes
    INTERNAL_SERVER_ERROR: {status_code: 500, error: ``},
    NOT_IMPLETEMENTED: {status_code: 501, error: ``},
    BAD_GATEWAY: {status_code: 502, error: ``},
    SERVICE_UNAVAILABLE: {status_code: 503, error: ``},
    GETAWAY_TIMEOUT: {status_code: 504, error: ``},
    HTTP_VERSION_NOT_SUPPORTED: {status_code: 505, error: ``},
    VARIANT_ALSO_NEGOTIATES: {status_code: 506, error: ``},
    INSUFFICIENT_STORAGE: {status_code: 507, error: ``},
    LOOP_DETECTED: {status_code: 508, error: ``},
    NOT_EXTENDED: {status_code: 510, error: ``},
    NETWORK_AUTH_REQUIRED: {status_code: 511, error: ``},

};
