module.exports = {

    //  1.x.x INFORMATIONAL HTTP Response Codes
    CONTINUE: {status_code: 100, error_type: ``},
    SWITCHING_PROTOCOLS: {status_code: 101, error_type: ``},
    PROCESSING: {status_code: 102, error_type: ``},
    EARLY_HINTS: {status_code: 103, error_type: ``},

    //  2.x.x SUCCESS HTTP Response Codes
    OK: {status_code: 200, error_type: ``},
    CREATED: {status_code: 201, error_type: ``},
    ACCEPTED: {status_code: 202, error_type: ``},
    NON_AUTHORITATIVE_INFO: {status_code: 203, error_type: ``},
    NO_CONTENT: {status_code: 204, error_type: ``},
    RESET_CONTENT: {status_code: 205, error_type: ``},
    PARTIAL_CONTENT: {status_code: 206, error_type: ``},
    MULTI_STATUS: {status_code: 207, error_type: ``},
    ALREADY_REPORTED: {status_code: 208, error_type: ``},
    IM_USED: {status_code: 226, error_type: ``},

    //  3.x.x REDIRECTION HTTP Response Codes
    MULTIPLE_CHOICES: {status_code: 300, error_type: ``},
    MOVED_PERMANENTLY: {status_code: 301, error_type: ``},
    FOUND: {status_code: 302, error_type: ``},
    SEE_OTHER: {status_code: 303, error_type: ``},
    NOT_MODIFIED: {status_code: 304, error_type: ``},
    USE_PROXY: {status_code: 305, error_type: ``},
    TEMPORARY_REDIRET: {status_code: 307, error_type: ``},
    PERMANENT_REDIRECT: {status_code: 308, error_type: ``},

    //  4.x.x CLIENT ERROR_typeS HTTP Response Codes
    BAD_REQUEST: {status_code: 400, error_type: ``},
    UNAUTHORIZATED: {status_code: 401, error_type: ``},
    PAYMENT_REQUIRED: {status_code: 402, error_type: ``},
    FORBIDDEN: {status_code: 403, error_type: ``},
    NOT_FOUND: {status_code: 404, error_type: ``},
    METHOD_NOT_ALLOWED: {status_code: 405, error_type: ``},
    NOT_ACCEPTABLE: {status_code: 406, error_type: ``},
    PROXY_AUTH_REQUIRED: {status_code: 407, error_type: ``},
    REQUEST_TIMEOUT: {status_code: 408, error_type: ``},
    CONFLICT: {status_code: 409, error_type: ``},
    GONE: {status_code: 410, error_type: ``},
    LENGTH_REQUIRED: {status_code: 411, error_type: ``},
    PRECONDITION_FAILED: {status_code: 412, error_type: ``},
    PAYLOAD_TOO_LARGE: {status_code: 413, error_type: ``},
    URI_TOO_LONG: {status_code: 414, error_type: ``},
    UNSUPPORTED_MEDIA_TYPE: {status_code: 415, error_type: ``},
    RANGE_NOT_SATSIABLE: {status_code: 416, error_type: ``},
    EXPECTATUIB_FAILED: {status_code: 417, error_type: ``},
    MISDIRECTED_REQUEST: {status_code: 421, error_type: ``},
    UNPROCESSABLE_ENTITY: {status_code: 422, error_type: ``},
    LOCKED: {status_code: 423, error_type: ``},
    FAILED_DEPENDENCY: {status_code: 424, error_type: ``},
    UPGRADE_REQUIRED: {status_code: 426, error_type: ``},
    PRECONDITION_REQUIRED: {status_code: 428, error_type: ``},
    TOO_MANY_REQUESTS: {status_code: 429, error_type: ``},
    REQUEST_HEADER_FIELDS_TOO_LARGE: {status_code: 431, error_type: ``},
    UNAVAILABLE_FOR_LEGAL_REASONS: {status_code: 451, error_type: ``},

    //  5.x.x SERVER ERROR_typeS HTTP Response Codes
    INTERNAL_SERVER_ERROR_type: {status_code: 500, error_type: ``},
    NOT_IMPLETEMENTED: {status_code: 501, error_type: ``},
    BAD_GATEWAY: {status_code: 502, error_type: ``},
    SERVICE_UNAVAILABLE: {status_code: 503, error_type: ``},
    GETAWAY_TIMEOUT: {status_code: 504, error_type: ``},
    HTTP_VERSION_NOT_SUPPORTED: {status_code: 505, error_type: ``},
    VARIANT_ALSO_NEGOTIATES: {status_code: 506, error_type: ``},
    INSUFFICIENT_STORAGE: {status_code: 507, error_type: ``},
    LOOP_DETECTED: {status_code: 508, error_type: ``},
    NOT_EXTENDED: {status_code: 510, error_type: ``},
    NETWORK_AUTH_REQUIRED: {status_code: 511, error_type: ``},

};
